package com.bullhorn.app;

public class Constants {


    public static final String AZURE_CONSUMER = "AZURE-CONSUMER";
    public static final String DATA_SWAPPER = "DATA-SWAPPER";
    public static final String DATA_VALIDATOR = "DATA-VALIDATOR";
    public static final String DATA_MAPPER = "DATA-MAPPER";


    public static final String AZURE_CONSUMER_THREAD_POOL_PREFIX = AZURE_CONSUMER + "-%s-";
    public static final String DATA_SWAPPER_THREAD_POOL_PREFIX = DATA_SWAPPER + "-All-";
    public static final String DATA_VALIDATOR_THREAD_POOL_PREFIX = DATA_VALIDATOR + "-%s-";
    public static final String DATA_MAPPER_THREAD_POOL_PREFIX = DATA_MAPPER + "-%s-";


    public static final String AZURE_CONSUMER_THREADPOOL_SCHEDULER_TERMINATION_TIME_INSECONDS = "AZURE_CONSUMER_THREADPOOL_SCHEDULER_TERMINATION_TIME_INSECONDS";
    public static final String DATA_SWAPPER_THREADPOOL_SCHEDULER_TERMINATION_TIME_INSECONDS = "DATA_SWAPPER_THREADPOOL_SCHEDULER_TERMINATION_TIME_INSECONDS";
    public static final String DATA_VALIDATOR_THREADPOOL_SCHEDULER_TERMINATION_TIME_INSECONDS = "DATA_VALIDATOR_THREADPOOL_SCHEDULER_TERMINATION_TIME_INSECONDS";
    public static final String DATA_MAPPER_THREADPOOL_SCHEDULER_TERMINATION_TIME_INSECONDS = "DATA_MAPPER_THREADPOOL_SCHEDULER_TERMINATION_TIME_INSECONDS";

    public static final String AZURE_CONSUMER_EXECUTE_INTERVAL = "AZURE_CONSUMER_EXECUTE_INTERVAL";
    public static final String DATA_SWAPPER_EXECUTE_INTERVAL = "DATA_SWAPPER_EXECUTE_INTERVAL";
    public static final String DATA_VALIDATOR_EXECUTE_INTERVAL = "DATA_VALIDATOR_EXECUTE_INTERVAL";
    public static final String DATA_MAPPER_EXECUTE_INTERVAL = "DATA_MAPPER_EXECUTE_INTERVAL";
    
    public static final String PNET_ASSIGNMENT_PROCESSOR_REST_URL = "PNET_ASSIGNMENT_PROCESSOR_REST_URL";
    public static final String AZURE_CONSUMER_QUEUE_NAME = "AZURE_CONSUMER_QUEUE_NAME";

}
